name: doctor_of_vetma
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  simple_animations: 
  bloc: null
  cached_network_image: null
  cloud_firestore: null
  conditional_builder_null_safety: null
  cupertino_icons: null
  dartz: null
  dio: null
  dropdown_button2: null
  equatable: null
  firebase_auth: null
  firebase_core: null
  firebase_database: null
  firebase_messaging: null
  firebase_storage: null

  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_getit: null
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: null
  fluttertoast: null
  font_awesome_flutter: null
  get_it: null
  google_fonts: null
  google_nav_bar: null
  google_sign_in: null
  hexcolor: null
  image_picker: null
  intl: ^0.18.1
  modal_bottom_sheet: ^2.1.2
  page_transition: null
  pin_code_fields: null
  shared_preferences: null

  smooth_page_indicator: null
  url_launcher: null
dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/animals/logo3.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/animals/
    - assets/doctor/
    - assets/doctor/icon/
    - assets/animals/logo3.png
  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
